update

diff --git a/s3/bash-scripts/destroy-bucket b/s3/bash-scripts/destroy-bucket
--- a/s3/bash-scripts/destroy-bucket
+++ b/s3/bash-scripts/destroy-bucket
@@ -1,4 +1,8 @@
 #!/usr/bin/env bash
+echo "== delete objects"
+
+# Exit immediately if any command returns a non-zero status
+set -e
 
 # Check for bucket name
 if [ -z "$1" ]; then
@@ -8,4 +12,9 @@ fi
 
 BUCKET_NAME=$1
 
-aws s3api delete-bucket --bucket $BUCKET_NAME
+aws s3api list-objects-v2 \
+--bucket $BUCKET_NAME \
+--query Contents[].Key \
+| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json
+
+aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json
